export const POPULAR_ARTISTS = [
  {
    label: "Hip-Hop and R&B",
    options: [
"Youngboy Never Broke Again",
"Juice WRLD",
"Lil Durk",
"Future",
"Lil Baby",
"Playboi Carti",
"$uicideBoy$",
"Lil Uzi Vert",
"Drake",
"Eminem",
"Lil Wayne",
"Jay-Z",
"Kanye West",
"A$AP Rocky",
"Kid Cudi",
"J. Cole",
"Kendrick Lamar",
"Gunna",
"Mac Miller",
"JID",
"Denzel Curry",
"Doechi",
"Vic Mensa",
"Isaiah Rashaad",
"Rick Ross",
"Joey Bada$$",
"Jeezy",
"Pusha T",
"21 Savage",
"Baby Keem",
"Freddie Gibbs",
"Nas",
"Lloyd Banks",
"Mobb Deep",
"MF DOOM",
"Conway The Machine",
"Run The Jewels",
"Killer Mike",
"Twista",
"Pimp C",
"Post Malone",
"Outkast",
"Tyler, The Creator",
"Shaboozey",
"Cardi B",
"Notorious BIG",
"2Pac",
"Snoop Dogg",
"Lupe Fiasco",
"GloRilla",
"Travis Scott",
"Don Toliver"
    ]
  },
  {
    label: "Pop",
    options: [
"Justin Bieber",
"Taylor Swift",
"The Weeknd",
"Billie Eilish",
"Ariana Grande",
"Bruno Mars",
"Ed Sheeran",
"Gracie Abrams",
"Harry Styles",
"Rihanna",
"Chappel Roan",
"Frank Ocean",
"Mariah Carey",
"Britney Spears",
"Michael Jackson",
"Prince",
"Beyonce",
"Charli xcx",
"Lady Gaga",
"Hozier",
"Modest Mouse",
"Amy Winehouse",
"Lola Young",
"Jessie Murph",
"Olivia Rodrigo",
"sombr",
"Tate McRae",
"SZA",
"Benson Boone",
"Dua Lipa",
"Lorde",
"Lana Del Rey",
"Teddy Swims",
"Sabrina Carpenter",
"Bad Bunny",
"Dasha",
"Miley Cyrus",
    ]
  },
  {
    label: "Classic Rock",
    options: [
"Eagles",
"Elton John",
"The Doors",
"The Beatles",
"Fleetwood Mac",
"Black Sabbath",
"Pink Floyd",
"The Rolling Stones",
"Ozzy Osbourne",
"Wham!",
"Toto",
"Aerosmith",
"Depeche Mode",
"Tears for Fears",
"Jefferson Airplane",
"Carlos Santana",
"Billy Joel",
"David Bowie",
"Bruce Springsteen",
"Aretha Franklin",
"Stevie Wonder",
"AC/DC",
"Queen",
"Bon Jovi",
"Guns N' Roses",
"The Rolling Stones",
"Tom Petty",
"Blondie",
"Earth, Wind, and Fire",
"R.E.M.",
"The Allman Brothers Band",
"Lynyrd Skynyrd",
"Guns N' Roses",
"Van Halen",
"The Beach Boys",
"The Clash",
"Ramones",
"Heart",
"The Grateful Dead",
"The Who",
"Led Zeppelin",
"U2",
    ]
  },
  {
    label: "Rock",
    options: [
"Linkin Park",
"Coldplay",
"Nirvana",
"Oasis",
"Foo Fighters",
"Green Day",
"Metallica",
"Radiohead",
"Artic Monkeys",
"Fall Out Boy",
"The Killers",
"The Strokes",
"The Shins",
"Alice in Chains",
"Pearl Jam",
"Rage Against The Machine",
"Brand New",
"Taking Back Sunday",
"Incubus",
"Red Hot Chili Peppers",
"Blink-182",
"The Cure",
"Oasis",
"No Doubt",
"Nine Inch Nails",
"Smashing Pumpkins",
"Soundgarden",
"Alice in Chains",
"The White Stripes",
"Paramore",
"Pearl Jam",
"Rage Against The Machine",
"Radiohead",
"Metallica",
"Neutral Milk Hotel"
]
},
{
 label: "Country",
 options: [
"Morgan Wallen",
"Alex Warren",
"Zac Bryan",
"Luke Combs",
"George Strait",
"Alan Jackson",
"Garth Brooks",
"Darius Rucker",
"Tim McGraw",
"The Chicks",
"Chris Stapleton",
"Johnny Cash",
  "Kacey Musgraves",
  "Megan Maroney",
  "Dolly Parton",
  "Ella Langley",
  "Brad Paisley",
  "Lainey Wilson",
  "Cody Johnson",
  "Shania Twain",
  "Toby Keith",
  "Chris Isaak",
  "Sturgill Simpson",
  "Jason Isbell",
  "Bailey Zimmerman",
  "Thomas Rhett",
  "Riley Green",
  "Ella Langley",
  "Jordan Davis",
  "Bonnie Tyler",
  "Gene Autrey",
  "Hank Williams",
  "Sam Hunt",
  "Maren Morris",
  "Jon Pardi",
  "Colter Wall",
  "Whitey Morgan and the 78's",
  "Little Big Town",
  "Brooks & Dunn",
  "Dustin Lynch",
 "Brett Eldredge",
 "Keith Urban",
 "Blake Shelton",
  "Kenny Chesney",
  "Zac Bryan Band",
"Jason Aldean",
"Eric Church",
"Miranda Lambert",


 ]
},
{
  label: "Folk & Indie",
  options: [
    "Townes Van Zandt",
    "Simon & Garfunkel",
    "Leonard Cohen",
    "Joni Mitchell",
    "Neil Young",
    "Gregory Alan Isakov",
    "Iron & Wine",
    "Jim Croce",
    "James Taylor",
    "Peter, Paul, and Mary",
    "Carole King",
    "Gordon Lightfoot",
    "John Prine",
    "Cat Stevens",
    "Dan Fogelberg",
    "Joan Baez",
    "Woody Guthrie",
    "Bob Dylan",
    "Crosby, Stills, and Nash",
    "The Tallest Man on Earth",
    "Brett Dennen",
    "Radical Face",
    "Bon Iver",
    "Bright Eyes"
  ]
},
{
  label: "Other",
  options: "Other"
}
];

export const POPULAR_GENRES = [
  "Pop",
  "Rock",
  "Hip Hop",
  "R&B",
  "Country",
  "Jazz",
  "Blues",
  "Folk",
  "Electronic",
  "Metal",
  "Punk",
  "Reggae",
  "Soul",
  "Indie",
  "Alternative",
  "Disco",
  "Funk",
  "Gospel",
  "Latin",
  "Classical",
  "Ambient",
  "Synthwave",
  "Lo-fi",
  "Trap",
  "Grime",
  "House",
  "Techno",
  "Dubstep",
  "Ska",
  "Grunge",
  "Emo",
  "Symphonic Rock",
  "Psychedelic Rock",
  "Progressive Rock",
  "Hardcore Punk",
  "New Wave",
  "Dream Pop",
  "Shoegaze",
  "Americana",
  "Bluegrass",
  "Other"
];
